//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShMI.BaseMain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDb : DbContext
    {
        public EntitiesDb()
            : base("name=EntitiesDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CURRENT_TRANSACTION> CURRENT_TRANSACTION { get; set; }
        public virtual DbSet<NCassa> NCassas { get; set; }
        public virtual DbSet<NObject> NObjects { get; set; }
        public virtual DbSet<NStruna> NStrunas { get; set; }
        public virtual DbSet<NTank> NTanks { get; set; }
        public virtual DbSet<PUMP_TOTALS> PUMP_TOTALS { get; set; }
        public virtual DbSet<READY_TRANSACTION> READY_TRANSACTION { get; set; }
        public virtual DbSet<ReCodesTable> ReCodesTables { get; set; }
        public virtual DbSet<SendMSG> SendMSGs { get; set; }
        public virtual DbSet<TANK_READING> TANK_READING { get; set; }
        public virtual DbSet<TankReading> TankReadings { get; set; }
        public virtual DbSet<Task_Device> Task_Device { get; set; }
        public virtual DbSet<TestTable> TestTables { get; set; }
    }
}
