//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShMI.BaseMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCassa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NCassa()
        {
            this.CURRENT_TRANSACTION = new HashSet<CURRENT_TRANSACTION>();
            this.PUMP_TOTALS = new HashSet<PUMP_TOTALS>();
            this.READY_TRANSACTION = new HashSet<READY_TRANSACTION>();
            this.TANK_READING = new HashSet<TANK_READING>();
        }
    
        public System.Guid Id { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public System.Guid NObjectId { get; set; }
        public int LastID { get; set; }
        public int CountReadLine { get; set; }
        public bool NCassa_Active { get; set; }
        public string Cash_type { get; set; }
        public string NObjectId_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CURRENT_TRANSACTION> CURRENT_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUMP_TOTALS> PUMP_TOTALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<READY_TRANSACTION> READY_TRANSACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TANK_READING> TANK_READING { get; set; }
        public virtual NObject NObject { get; set; }
    }
}
