//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShMI.BaseMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTank()
        {
            this.SendMSGs = new HashSet<SendMSG>();
        }
    
        public System.Guid Id { get; set; }
        public string TankNumber { get; set; }
        public string Grade { get; set; }
        public string Grade_Name { get; set; }
        public System.Guid NStrunaId { get; set; }
        public string Max_Volume { get; set; }
        public string WaterLevel_Allow { get; set; }
        public string Water_alarm { get; set; }
        public string Level_alarm { get; set; }
    
        public virtual NStruna NStruna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendMSG> SendMSGs { get; set; }
    }
}
