//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShMI.BaseMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Device
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> Date_LastLine_Struna { get; set; }
        public Nullable<System.DateTime> Date_LastLine_Cassa { get; set; }
        public string Name_Task { get; set; }
        public int Period_Task { get; set; }
        public string Type_Device { get; set; }
        public string Zip_Dir { get; set; }
        public System.Guid NObjectId { get; set; }
        public int CountDaySave { get; set; }
        public Nullable<int> Period_Ping { get; set; }
        public Nullable<bool> Is_TaskOk { get; set; }
        public string Status { get; set; }
        public string StatusMsg { get; set; }
        public string Type_Task { get; set; }
    
        public virtual NObject NObject { get; set; }
    }
}
